const AUTH = {
  LOGIN: 'customer/signin/',
  VERIFY: 'customer/verify-otp/',
  REGISTER: 'customer/update-profile/',
  REFRESH: 'customer/refresh-token-access/',
};
const ENDPOINTS = {
  AUTH,
  MAKE_A_TRIP: 'listing/listing-filter/',
  HOME: 'customer/dashboard/',
  SERVICES: 'customer/service_type/',
  SINGLE_SERVICE: 'customer/single-servicetype/',
  LOUNGES_COORDINATES_LIST: 'listing/listings-travlounge/',
  LOUNGES_CATEGORY: 'listing/listings-category/',
  LOUNGE_DETAILS: 'listing/listing-single-filter/',
  QR_CHECK: 'customer/generateqr_checking/',
  WALLET: 'customer/wallet/',
  WALLET_UPDATE: 'customer/wallet/',
  QR_WALLET_DETAILS: 'customer/wallet-subs-usage/',
  PROFILE: 'customer/customerprofile/',
  AVALABLE_SLEEPINGPOD: 'customer/all-available-pods/',
  SUBSCRIBE: 'customer/subscribe/',
  USER_DETAILS: 'customer/update-profile/',
  ROUTE_STATION_LIST: 'listing/elastic-search-filter/',
  PACKAGES_LIST: 'customer/packages-subscrition/',
  SERVICE_LIST: 'customer/home_listing/',
  SERVICE_DETAIL: 'customer/fetch_listing/',
  ADD_REVIEW: 'customer/rating_create/',
  SLEEPING_POD_LIST: 'sleeping_pod/sleeping-pods/search/',
  CATEGORY_LIST: 'customer/listing_category/',
  COUPON: 'customer/coupon-redemption/',
  DELETE_ACCOUNT: 'customer/delete-account/',
  SLEEPING_POD_DETAIL: 'sleeping_pod/sleeping-pods/search/',
  SLEEPING_POD_PRICE: 'sleeping_pod/sleeping_pod_availability_price/',
  CREATE_ORDER_SLEEPING_POD: 'sleeping_pod/booking-payment/',
  BOOKINGS: 'customer/user-bookings/',
  SLEEPING_POD_BOOKINGS: 'sleeping_pod/booking-details/',
  BOOKING_DETAIL: 'customer/event-detail/',
  SLEEPING_POD_BOOKING_CANCEL: 'sleeping_pod/booking-cancel/',
  CAR_WASH_BOOKING_CANCEL: 'car_wash/booking-cancel/',
  SLEEPING_POD_RE_PAYMENT: 'sleeping_pod/get-razorpay-id/',
  CREATE_SERVICE_PAYMENT: 'customer/toloo/razorpay/order/',
  VERIFY_SERVICE_PAYMENT: 'customer/toloo/razorpay/verify/',
  CONFIRM_TOLOO_EVENT: 'customer/confirm-toloo-event/',
  ACTIVE_SUBSCRIPTIONS: 'customer/subscriptions/active/',
  REFRESH: 'customer/refresh-token-access/',
  CAR_WASH_SERVICES: 'car_wash/services/',
  CAR_WASH_BOOKING: 'car_wash/booking-payment/',
  CAR_WASH_TIME_SLOTS: 'car_wash/timeslot/',
};

export default ENDPOINTS;
